### PR TITLE
Feat/footer

### PR DESCRIPTION
**Pull request by luizabchagas**
## Description

[Trello Task - Footer Desktop and Mobile](https://trello.com/c/59wE9jlr/105-create-footer-section-for-match4action-website-mobile-and-desktop-screens)

Ready for Code Review and Merge.

## Expected Behavior

Footer section rendering at both mobile and desktop versions.

## Screenshots

WhatsApp Image 2023-04-29 at 17 05 49 (1)
WhatsApp Image 2023-04-29 at 17 05 49

### CODE REVIEW

**Comment by joaorpereira** [comment]
image

Ask Diana about the label "Site Map" I think this is wrong. Also update the date

**Comment by joaorpereira** [comment]
image

My screen is bigger, I think will be good have a different approach here instead of using image, make it using CSS, pr ask Diana to provide a bigger image ok?

**Comment by joaorpereira** [comment]
image

Ask Diana if makes sense show those buttons for a logged user.

**Comment by luizabchagas** [comment]
Updated for 2023 and changed the CSS measurement unit to percentages, so I believe the bigger screen's issue has been solved.  I will reach out to Diana regarding the remaining adjustments.

**Comment by luizabchagas** [comment]
Issues with backend are solved and I was able to test footer as a logged user to make the necessary adjustments.

Fix: Log Out button is OK.
Fix: Responsive footer is OK.

I'm going to ask Diana about the "Site Map" 

Captura de tela 2023-08-15 083317

**Pull request merged**
